### ISSUE TITLE
Add ability to blackout and highlight regions

### ISSUE THREAD

**Issue by martindsouza** [Dani3lSun/apex-plugin-apexscreencapture#2]
Google's feedback tools allows the ability to blackout and highlight areas. this would be similar to the 1.2 feature of selecting a given area only.

**Comment by Dani3lSun** [comment]
Hi Martin,
I implemented this or kind of this in a new version (not in Git so far). Can you please test it and give me feedback?
Link: https://apex.oracle.com/pls/apex/f?p=57743:15
Just click the button "Capture with DOM UI Selector" and select an area...

Regards
Daniel

btw: Happy new year!;)

**Comment by Dani3lSun** [comment]
Ok, the changes are now commited: 4affce488d5d6d4cd1ed5f40ab6e281ecefbc57e
Added options to pick a border color of your choice / fill the selector´s content with light transparent color (based on border color - 30% darker)...

**Comment by martindsouza** [comment]
@Dani3lSun Happy new years as well.

I just tested the above link and didn't see the option to pick color or blackout an area. Another way of looking at this is:
- Select the entire report
- Black out a few sensitive rows or columns in the report (either draw or div select).

**Comment by Dani3lSun** [comment]
Hi @martindsouza 
I think I misunderstood your initial feedback. To my last changes:
1) Border color of selector can be selected in the plugin settings in dev env:
<img width="200" alt="page_designer" src="https://cloud.githubusercontent.com/assets/698942/12074165/6b34f37a-b145-11e5-91ea-2f6a06be579d.png">
2) fill content is an option to highlight the complete area instead of the outline only (like chrome dev tools), here´s a comparison between outline only and with fill content option (content color is 30% darker and transparent):
<img width="600" alt="screen_02" src="https://cloud.githubusercontent.com/assets/698942/12074169/b7607bfc-b145-11e5-9c6d-ab757d233b8f.png">

I think I mixed up highlighting with blackout an area...^^
Blackout an area is not that simple, because html2canvas renders the complete DOM from given selector downwards the DOM tree. Maybe I can implement a attribute to blur the contained text of an selected region, than html2canvas will render the blurred text that is not readable...What do you think?

**Comment by Dani3lSun** [comment]
Seems that html2canvas has an option for that. Simply add

```
data-html2canvas-ignore="true"
```

to an element prevents it from getting rendered...
see: niklasvh/html2canvas@7c0b893564ea139005405b22d2ece99588663d7f

**Comment by martindsouza** [comment]
I'll mark this as closed for now. If I find exactly what Google uses in its feedback tool I'll let you know.
