### ISSUE TITLE
Different output from Safari and Firefox

### ISSUE THREAD

**Issue by ChrisLeitner** [Dani3lSun/apex-plugin-apexscreencapture#6]
Hello!
I found some problems when rendering an APEX-Calender.
### Expected behavior

I'm trying to export an APEX-Calendar into PNG and getting different / wrong results from Firefox and Safari.
### Actual behavior

[Difference.pdf](https://github.com/Dani3lSun/apex-plugin-apexscreencapture/files/378109/Difference.pdf)
Safari: some background-color is a bit short (see the green background at saturday / sunday)
Firefox: background-color is applied to whole cell and for one more line then it should be.

HTML-Source:
[Montageplan Kalender Druckansicht (Test).html.txt](https://github.com/Dani3lSun/apex-plugin-apexscreencapture/files/378125/Montageplan.Kalender.Druckansicht.Test.html.txt)
### Firefox 47.0.1 and Safari 9.1.2 both on OS X 11.6

kind regards
Chris

**Comment by Dani3lSun** [comment]
Hi @ChrisLeitner 
I looked into that behavior and it seems that it is not possible without changing the html of your page. This plugin uses html2canvas for taking a screenshot of the page as it is. This means it creates a canvas object with the help of the actual browser engine, this also means it could be different in different browsers...
My experience was that it works best in webkit browsers like Chrome or Safari...But a 100% correct screenshot will likely be impossible, because it renders the page again in a canvas...

Hope that helps!

**Comment by ChrisLeitner** [comment]
Thank's for the info - doesn't solve my problem but I see that it's not possible to address the issue within the plugin.

**Comment by Dani3lSun** [comment]
Yeah sorry for that...Hopefully html2canvas gets an update, this version is already older...
